version: "3.3"
services:
  jupyterlab:
    build: .
    ports:
      - 8888:8888
    volumes:
      - ~/.nanopub:/root/.nanopub

  mockworkflowhub:
    image: library/python:3.7-alpine
    volumes:
      - ./demo:/web
    ports:
      - 8080:8080
    command: python -m http.server --directory /web 8080
